# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/salestracker
spring.datasource.username=postgres
spring.datasource.password=12345678

# Hibernate crea/actualiza las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Muestra las queries SQL en la terminal
spring.jpa.show-sql=true

# Mensaje de error detallado
server.error.include-message=always